name: game_common
description: A starting point for Dart libraries or applications.
version: 1.0.0
publish_to: none
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.2.6

# Add regular dependencies here.
dependencies:
  uuid: ^4.3.3
  # path: ^1.8.0

  rondas_relampago:
    path: "../rondas_relampago"

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
